<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-02-28 at 22:57:34.
 */

/*require_once '../src/Sorter.php';
require_once '../src/BoardingCard.php';*/

require_once './src/Sorter.php';
require './src/BoardingCard.php';

class SorterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Sorter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $test = [
            [
                "from" => "cairo",
                "to" => "dubai",
            ],
            [
                "from" => "abu dhabi",
                "to" => "paris",
            ],
            [
                "from" => "dubai",
                "to" => "abu dhabi",
            ],
            [
                "from" => "paris",
                "to" => "london",
            ],
        ];
        $this->object = new Sorter($test);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Sorter::get_trip
     * @todo   Implement testGet_trip().
     */
    public function testGet_trip() {


        $result = $this->object->get_trip();
        $expected = [
            [
                "from" => "cairo",
                "to" => "dubai",
            ],
            [
                "from" => "dubai",
                "to" => "abu dhabi",
            ],
            [
                "from" => "abu dhabi",
                "to" => "paris",
            ],
            [
                "from" => "paris",
                "to" => "london",
            ],
        ];
        $this->assertTrue($result == $expected);
    }

}
